name: CI/CD Pipeline - Tienda Perritos

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Paso de "Profundización": Build multietapa y optimizado
      - name: Construir y subir imagen Backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/tienda-backend:${{ github.sha }} ./backend
          docker push $ECR_REGISTRY/tienda-backend:${{ github.sha }}

      # Automatización del despliegue: Aquí es donde ECS toma la nueva imagen
      - name: Desplegar en ECS
        run: |
          aws ecs update-service --cluster ep3-cluster \
          --service ep3-backend-service \
          --force-new-deployment
